# Generated by Django 3.2 on 2021-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(max_length=100)),
                ('advert_file', models.FileField(null=True, upload_to='videos/')),
                ('advert_image', models.ImageField(null=True, upload_to='thumbnails/')),
                ('advert_category', models.CharField(choices=[('Sports', 'Sports'), ('Technology', 'Technology'), ('Health', 'Health'), ('DIY', 'DIY')], max_length=30)),
                ('advert_budget', models.FloatField(null=True)),
                ('advert_slug', models.SlugField(blank=True, max_length=360, null=True, unique=True)),
                ('advert_views', models.IntegerField(default=0, null=True)),
                ('advert_gender_male', models.IntegerField(default=0)),
                ('advert_gender_female', models.IntegerField(default=0)),
                ('advert_gender_other', models.IntegerField(default=0)),
                ('advert_cost', models.FloatField(default=0)),
                ('advert_uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manage.business')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('advert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
            ],
        ),
        migrations.CreateModel(
            name='ViewedAdverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manage.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.survey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manage.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer_type', models.CharField(choices=[('RADIO_SELECT', 'RADIO_SELECT'), ('TEXT', 'TEXT')], max_length=30)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_title', to='adverts.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=250)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_related_to_answer', to='adverts.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=450)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_manage.consumer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.question')),
                ('survey_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adverts.surveyresponse')),
            ],
        ),
    ]
