# Generated by Django 3.2 on 2021-06-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Technology', 'Technology'), ('Health', 'Health'), ('DIY', 'DIY'), ('Gaming', 'Gaming'), ('Music', 'Music'), ('Books', 'Books'), ('Art', 'Art'), ('Science', 'Science'), ('Architecture', 'Architecture'), ('Business', 'Business'), ('History', 'History'), ('Finance', 'Finance'), ('Biology', 'Biology'), ('Languages', 'Languages')], max_length=30),
        ),
    ]
